apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: petclinic-2
  labels:
    team: petclinic-frontend
spec:
  selector:
    matchLabels:
        app: petclinic-app-2
  endpoints:
    - port: petclinic-port-2
      path: '/manage/prometheus'

